function upSizeS() {
    document.getElementById("size-S").className = "size-item-choosen";
    document.getElementById("size-M").className = "size-item";
    document.getElementById("size-L").className = "size-item";
}

function upSizeM() {
    document.getElementById("size-M").className = "size-item-choosen";
    document.getElementById("size-S").className = "size-item";
    document.getElementById("size-L").className = "size-item";
}

function upSizeL() {
    document.getElementById("size-L").className = "size-item-choosen";
    document.getElementById("size-M").className = "size-item";
    document.getElementById("size-S").className = "size-item";
}