function upSizeS() {
    document.getElementById("size-S").className = "size-item-choosen";
    document.getElementById("size-M").className = "size-item";
    document.getElementById("size-L").className = "size-item";
}

function upSizeM() {
    document.getElementById("size-M").className = "size-item-choosen";
    document.getElementById("size-S").className = "size-item";
    document.getElementById("size-L").className = "size-item";
}

function upSizeL() {
    document.getElementById("size-L").className = "size-item-choosen";
    document.getElementById("size-M").className = "size-item";
    document.getElementById("size-S").className = "size-item";
}

function upSize1() {
    document.getElementById("size-1").className = "size-item-choosen";
    document.getElementById("size--").className = "size-item";
    document.getElementById("size-0").className = "size-item";
}

function upSizeTru() {
    document.getElementById("size--").className = "size-item-choosen";
    document.getElementById("size-1").className = "size-item";
    document.getElementById("size-0").className = "size-item";
}

function upSize0() {
    document.getElementById("size-0").className = "size-item-choosen";
    document.getElementById("size-1").className = "size-item";
    document.getElementById("size--").className = "size-item";
}